// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package org.fidelis.animal.web.feed.add;

import java.util.ArrayList;
import java.util.Collection;
import javax.faces.model.SelectItem;
import org.fidelis.animal.ServiceLocator;
import org.fidelis.animal.model.feed.FeedType;

/**
 * @see org.fidelis.animal.web.feed.add.AddFeedController
 */
public class AddFeedControllerImpl
        extends AddFeedController {

    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8907523121169935452L;

    /**
     * @see
     * org.fidelis.animal.web.feed.add.AddFeedController#loadOptions(java.lang.String
     * type)
     */
    @Override
    public void loadOptions(LoadOptionsForm form) throws Throwable {
        try {
            final Collection typeBackingList = new ArrayList<SelectItem>();
            typeBackingList.addAll(FeedType.literals());
            form.setTypeBackingList(typeBackingList);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @see
     * org.fidelis.animal.web.feed.add.AddFeedController#add(java.lang.String
     * type, java.lang.Long id, java.lang.String name, java.lang.String code,
     * java.lang.String description, java.lang.String intakeWeight,
     * java.lang.String intakeRate)
     */
    @Override
    public void add(AddForm form) throws Throwable {
        try {
            ServiceLocator.instance().getFeedService().add(form.getType(), form.getCode(),
                    form.getName(), form.getDescription(), form.getIntakeWeight(),
                    form.getIntakeRate());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
